### ISSUE TITLE
Update MAINTAINERS file

### ISSUE THREAD

**Issue by dave-tucker** [docker/go-plugins-helpers#132]
I'm listed as a maintainer but:

1. I don't have merge access anymore
1. I don't have the time to maintain this repo

Please remove me, and update the MAINTAINERS file to reflect who is actually maintaing this repo :wink:

**Comment by thaJeztah** [comment]
👋 my team got access to this repository now; I opened https://github.com/docker/go-plugins-helpers/pull/139 to get you off the list; thanks for the wait @dave-tucker ❤️ ❤️ ❤️
