### ISSUE TITLE
Add IPAM Driver helpers

### ISSUE THREAD

**Issue by clinta** [docker/go-plugins-helpers#16]
It'd be nice if there were similar helper functions for easily creating an IPAM plugin.

**Comment by dave-tucker** [comment]
@clinta yep, I think @nerdalert might be working on that...

**Comment by clinta** [comment]
I've made some progress on it myself, I'm just now starting on my actual ipam plugin so I can test it.

https://github.com/clinta/go-plugins-helpers/blob/ipam-helper/ipam/api.go

**Comment by nerdalert** [comment]
hey guys, similar to @clinta approach I have a new module to keep a similar pattern as the others. Seem reasonable to you all?

**Comment by dave-tucker** [comment]
Closed by #25
