### ISSUE TITLE
Not clear which fields need to be populated for Volume.Response 

### ISSUE THREAD

**Issue by suryagaddipati** [docker/go-plugins-helpers#41]
Looks like all responses use [this](https://github.com/docker/go-plugins-helpers/blob/master/volume/api.go#L30-L35) interface for responses. Would it be possible to split that response interface into  multiple interfaces that only has specific fields required by the response ( eg : `Get` vs `List`)

**Comment by krish7919** [comment]
Currently, I fill only the responses that are required, as specified in the documentation.
It would make it easier to split them; however, I don't mind the one big response struct. :)

**Comment by dave-tucker** [comment]
Yes it would be possible to split it - we've done this in other plugins, for example: https://github.com/docker/go-plugins-helpers/blob/master/network/api.go#L112

We'd welcome a PR to do this.
