### ISSUE TITLE
Shim is not building

### ISSUE THREAD

**Issue by mdong** [docker/go-plugins-helpers#46]
Hi, 

Shim is currently not building, due to the added ID for Mount and Unmount.

https://github.com/docker/go-plugins-helpers/blob/master/volume/shim.go#L92

I assume it is similar to this? 

https://github.com/docker/docker/commit/2b6bc294fc7f9e08a9091833b021b7d2a01ad2a6

**Comment by thaJeztah** [comment]
ping @cpuguy83 PTAL

**Comment by deviantony** [comment]
Yeah, having the same issue at the moment. I'm trying to build my own plugin and I can't built it.

**Comment by cpuguy83** [comment]
Yep it needs to be updated.
You should really checkout a release tag of docker before trying to build.

**Comment by runcom** [comment]
can this be closed given we moved the shim out?

**Comment by calavera** [comment]
Close it. It looks like I don't have credentials to do it myself.

**Comment by runcom** [comment]
is this because of fail in https://github.com/docker/go-plugins-helpers/pull/48? (forget my comment above)
