### ISSUE TITLE
no buildable Go source files

### ISSUE THREAD

**Issue by CWSpear** [docker/go-plugins-helpers#50]
Trying to build a plugin using the `helpers`, but getting this error:

```
# go build -v
../github.com/docker/go-plugins-helpers/sdk/unix_listener.go:12:2: no buildable Go source files in /go/src/github.com/coreos/go-systemd/util
```

I can definitely see there are files there:

```
# ls  /go/src/github.com/coreos/go-systemd/util
util.go
```

I'm not super familiar with Go, so I don't know what it means "no buildable files," but from what I can find on the internet, there is maybe a bad dependency or something...?

I am using the `docker golang:onbuild` image to try and have a clean environment.

**Comment by thaJeztah** [comment]
"no buildable files," can indicate that there's no source files for your architecture; what platform / architecture are you trying to build this on?

**Comment by CWSpear** [comment]
Thanks for the quick response!

`linux/amd64` (since it's a Docker plugin). This _used_ to work on my Mac. I started to try the Docker image mentioned since that's the same platform/arch as I'm targeting.

Ok, so trying to create a reduced case and it looks like the culprit is `export CGO_ENABLED=0`. I want the binary to be runnable on Docker `alpine` images, and again, I'm no Go developer, but my understanding is I need that flag so it won't do dynamic linking and work in `alpine`.

Here's the repo I'm trying to build: https://github.com/CWSpear/local-persist

So trying to build without `CGO_ENABLED` flag on Mac (but setting `GOOS` and `GOARCH` to `linux` and `amd64` respectively) or enabling `CGO_ENABLED` on Linux, I am seeing this error.

To reproduce yourself:

```
git clone https://github.com/CWSpear/local-persist
cd local-persist
docker run -it -v `pwd`:/go/src/app  golang:onbuild bash
# now, you'll be inside the docker image, run:
export CGO_ENABLED=0
go get -v -d
go build -v .
```

**Comment by thaJeztah** [comment]
Hm, no direct suggestions, but perhaps @calavera, @runcom or @vdemeester are better suited to help you further.

**Comment by dave-tucker** [comment]
`go build -v` - if you are running this from OSX, it looks like you are building for OSX.
You may want to set the `GOOS` and `GOARCH` variables in `go build` (see [here](http://dave.cheney.net/2015/08/22/cross-compilation-with-go-1-5))
Otherwise, you can do what I do - build your project in a Docker container instead ;)

**Comment by CWSpear** [comment]
Sorry, I should have mentioned that I do set the `GOOS` and `GOARCH`.

I have just been building it inside a container lately tho.
