### ISSUE TITLE
Support custom methods for volume plugins

### ISSUE THREAD

**Issue by govint** [docker/go-plugins-helpers#58]
Docker defines a set of requests for volume plugins and those are supported in go-plugin-helpers. But volume plugins may implement more than just the set of commands that docker defines for a volume plugin. These additional commands allow the volume plugin to surface more of their volume mgmt capabilities for users. And these additional commands can be addressed directly to the volume plugin.

Key use cases are:
a. Allow third party tools to be developed for management of persistent volumes that don't necessarily need to be implemented via docker.
b. Provide a way for volume plugin providers to expose capabilities that can help with (1).
c. Volume plugin provider's feature development doesn't need to be in sync with docker releases. Since volume plugins are external software, features in those can be async to docker releases and this capability allows those features to be available sooner.

This issue is a request to add capability to accept custom command and arguments as requests and pass on response blobs to the requester. There is no format or structure imposed on the request and response.

**Comment by govint** [comment]
@cpuguy83

**Comment by govint** [comment]
@cpuguy83 can you comment on this issue, I've got changes I can post as a PR. Especially for features around surfacing volume metrics that can't be returned to Docker.

**Comment by cpuguy83** [comment]
@govint Personally, I don't think it's something we'd want here.
This is plugin-helpers for docker. If Docker can't/isn't going to take advantage of something then it shouldn't be in this repo.

That said, this repo is Apache2 licensed  and you can definitely fork and add the features you need to it.

**Comment by dave-tucker** [comment]
Agree with @cpuguy83. If new features are to be added to the plugin API this needs to be done upstream in docker/docker. This repo is focussed on making it easy to create plugins based on that API and not to add any additional functionality
