### ISSUE TITLE
troubles on my plugin

### ISSUE THREAD

**Issue by sunjian19891** [docker/go-plugins-helpers#62]
docker version: docker 1.12 

hi . i have two questions:
1.  docker plugin : docker "plugin" is not docker command , I don't know why 
 and  dir: /var/lib/docker/plugin don't exist in my docker 

2.  i have pull "clusterhq/flocker-core"  image,  

when i create a volume using flocker driver:docker volume create --name flocker-volume -d clusterhq/flocker-core, it prompt errors：Error response from daemon: create flocker-volume: create flocker-volume: Error looking up volume plugin clusterhq/flocker-core: legacy plugin: plugin not found。

**Comment by dave-tucker** [comment]
Hi @sunjian19891. This repo is for plugin developers rather than users. If you have an issue with docker, you should open an issue on github.com/docker/docker. If your issue is with a specific pluign, your best bet is to contact the plugin author directly.
