### ISSUE TITLE
Authorization plugin does not work on Mac OS X

### ISSUE THREAD

**Issue by artsf** [docker/go-plugins-helpers#78]
I built a sample plugin using "github.com/docker/go-plugins-helpers/authorization" package.
See https://github.com/artsf/docker-auth-test and it is not getting triggered.
Plugin builds, created and enabled OK, but then it just doesn't work at all.
It does not produce any stdout output and does not block any images from running.

Did I miss anything?

OS:
Mac OS X 10.11.6 (build: 15G1421)

Go:
go version go1.8 darwin/amd64

Docker:
Docker version 17.03.1-ce, build c6d412e

Docker UI:
Version 17.03.1-ce-mac5 (16048)
Channel: stable
b18e2a50cc

Diagnostics:
```
Docker for Mac: version: 17.03.1-ce-mac5 (b18e2a50c)
macOS: version 10.11.6 (build: 15G1421)
logs: /tmp/2439AFEC-179A-4471-9766-DEEE420D4146/20170405-165618.tar.gz
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk
```

**Comment by artsf** [comment]
@runcom can you please advise? :)

**Comment by hsluoyz** [comment]
@artsf hi,

I created a Docker auth plugin named [casbin-authz-plugin](https://github.com/casbin/casbin-authz-plugin). It is based on [casbin](https://github.com/hsluoyz/casbin) which supports models like ACL, RBAC, ABAC.

Maybe it works for you:)

**Comment by Dean-Christian-Armada** [comment]
@hsluoyz 

Do you have any steps that will make your Docker auth plugin work in mac? It throws the error below when following your steps

```
install: /lib/systemd/system: No such file or directory
make: *** [install] Error 71

```

**Comment by thaJeztah** [comment]
Did you build/compile the plugin on OS X or on Linux? Otherwise you'd be trying to run an OS X binary inside the linux machine where the daemon runs

**Comment by Dean-Christian-Armada** [comment]
@thaJeztah , I also tried in the xhyve virtual machine where the docker engine is located but still there is no `/lib/systemd/system`.

**Comment by hsluoyz** [comment]
@Dean-Christian-Armada I don't own an OS X to test it. Maybe the shell commands between Linux and OS X are different. Can you try to figure out which path should be modified to an OS X version?

**Comment by thaJeztah** [comment]
Does the plugin interact with systemd? If so, that's expected, as Docker for Mac does not use systemd; may be something to take into account in the plugin, as systemd is not present on all platforms/distros

**Comment by Dean-Christian-Armada** [comment]
@hsluoyz , it's ok. Maybe I can check this more thoroughly for MAC.

@thaJeztah , yeah you are right. Maybe we can check something out as an alternative for MAC.

**Comment by thaJeztah** [comment]
Let me go ahead and close this issue, but feel free to continue the conversation 👍

**Comment by artsf** [comment]
Why close if it was not implemented?

**Comment by lox** [comment]
I'm having exactly the same issue, is there a canonical issue to track this @thaJeztah if this issue wasn't valid?

**Comment by lox** [comment]
Did you end up getting this working @artsf?

**Comment by artsf** [comment]
Yes, it worked in certain configurations. I think one of latest commits fixed it.
